Add ChaCha and Salsa intrinsics.
idaviddesmet/NaCl.Core pull request #128
Opened 2022-10-11 17:21 UTC by TimothyMakkison

Added @macaba intrinsics implementation #58 for ChaCha20. Salsa20 has since been added so I created `Salsa20BaseIntrinsics` based on macaba's work.

- Added ChaCha20 & Salsa20
- Added benchmarks for Salsa20 and XSalsa20
- Added checks for intrinsics support and failovers.

2022-10-12 00:55 UTC, daviddesmet commented
Thanks for the contribution and for adding Salsa20 intrinsics too!
I wonder if we can reduce the method complexity of those intrinsics ones by breaking them apart. Afaik, the initial code was grabbed from another repository which I currently don't recall.

There's also XSalsa20 over there but I haven't promoted those to stable since I felt it needed more tests. The target was to also support XSalsa20Poly1305.

Regarding testing of intrinsics turned on and off, yes, it was something around `COMPlus_EnableAVX`, I'm not sure since I looked at this a while ago. For the CI, we might need to add tests for running with and without intrinsics I guess.

Btw, do you have some benchmark numbers you can share to see the perf increase?

I might need to take a look at why the Azure CI failed with Windows only.

2022-10-12 22:42 UTC, TimothyMakkison commented
> I wonder if we can reduce the method complexity of those intrinsics ones by breaking them apart.
> 

I've split Intrinsics up by chunk size and altered `ChaCha64` and `Salsa64` to add `HChaCha`/`HSalsa` support. Aside from that I haven't changed the other methods. I guess I could extract some of the Xor/Store/Unpack methods and give them nicer names. I'll add `ProcessKeyStreamIntrinsics`, the changes to the 64 chunk methods should make it painless.

> There's also XSalsa20 over there but I haven't promoted those to stable since I felt it needed more tests. The target was to also support XSalsa20Poly1305.
> 
> Regarding testing of intrinsics turned on and off, yes, it was something around `COMPlus_EnableAVX`, I'm not sure since I looked at this a while ago. For the CI, we might need to add tests for running with and without intrinsics I guess.

I'll take a look, I've never used env variables in unit tests before, hopefully Google will help.

> 
> Btw, do you have some benchmark numbers you can share to see the perf increase?
> 
My numbers are from some benchmarks I did yesterday. Sorry about the quality, my laptops about to die 😅

### Salsa
![image](https://user-images.githubusercontent.com/49349513/195461071-926afe26-41fd-4203-a7f4-b71b08bd253b.png)

### ChaCha
![image](https://user-images.githubusercontent.com/49349513/195461306-0ad9b553-187e-449d-8d4a-fb8ef9e7124c.png)

2022-10-13 00:21 UTC, daviddesmet commented
> I've split Intrinsics up by chunk size and altered `ChaCha64` and `Salsa64` to add `HChaCha`/`HSalsa` support. Aside from that I haven't changed the other methods. I guess I could extract some of the Xor/Store/Unpack methods and give them nicer names. I'll add `ProcessKeyStreamIntrinsics`, the changes to the 64 chunk methods should make it painless.

Sounds good, thanks a lot for the effort you are putting into this.

> I'll take a look, I've never used env variables in unit tests before, hopefully Google will help.

If you run the benchmarks from Powershell or cmd via `dotnet run`, you can set the variable using `set VARIABLE=VALUE` before the `dotnet` command.

> My numbers are from some benchmarks I did yesterday. Sorry about the quality, my laptops about to die 😅
> 
> ### Salsa
> ![image](https://user-images.githubusercontent.com/49349513/195461071-926afe26-41fd-4203-a7f4-b71b08bd253b.png)
> 
> ### ChaCha
> ![image](https://user-images.githubusercontent.com/49349513/195461306-0ad9b553-187e-449d-8d4a-fb8ef9e7124c.png)

Thanks for sharing those, the numbers look nice :)

2022-10-16 23:28 UTC, TimothyMakkison commented
I've experimented with a [refactor](https://github.com/TimothyMakkison/NaCl.Core/tree/experimental_intrinsics_refactor) that treats `ChaCha20Base` and `Salsa20Base` as a proxy for the internal `...Core` and `...CoreItrinsics` methods. It removes the intrinsics checks and preprocessor spam but arguably makes the code harder to read, I don't think I changed any externally visible apis.

I'm planning on creating some general tests for intrinsics code and relying on the CI with different flags enabled to do a thorough check. Ideally I'd configure XUnit to run the tests/test classes again with different flags but it doesn't seem supported 🤷

2022-11-08 01:33 UTC, daviddesmet requested changes

2022-11-08 01:33 UTC, daviddesmet commented on src/NaCl.Core/Base/ChaCha20Base.cs
> +        readonly IChaCha20Core _chaCha20Core;
Could you make this access modifier implicit?

2022-11-08 01:33 UTC, daviddesmet commented on src/NaCl.Core/Base/ChaCha20Base.cs
> +#if INTRINSICS
I wonder if we do need the preprocessor directive since we are checking if the hardware supports it

2022-11-08 01:33 UTC, daviddesmet commented on src/NaCl.Core/Base/ChaCha20BaseIntrinsics.cs
> +﻿#if INTRINSICS
I wonder if we do need the preprocessor directive since we are checking if the hardware supports it

2022-11-08 01:33 UTC, daviddesmet commented on src/NaCl.Core/Base/ChaChaCore/ChaCha20CoreIntrinsics.cs
> +﻿#if INTRINSICS
I wonder if we do need the preprocessor directive since we are checking if the hardware supports it

2022-11-08 01:33 UTC, daviddesmet commented on src/NaCl.Core/Base/ChaChaIntrinsics/ChaCha256.cs
> +﻿#if INTRINSICS
I wonder if we do need the preprocessor directive since we are checking if the hardware supports it

2022-11-08 01:33 UTC, daviddesmet commented on src/NaCl.Core/Base/ChaChaIntrinsics/ChaCha512.cs
> +﻿#if INTRINSICS
I wonder if we do need the preprocessor directive since we are checking if the hardware supports it

2022-11-08 01:33 UTC, daviddesmet commented on src/NaCl.Core/Base/ChaChaIntrinsics/ChaCha64.cs
> +﻿#if INTRINSICS
I wonder if we do need the preprocessor directive since we are checking if the hardware supports it

2022-11-08 01:33 UTC, daviddesmet commented on src/NaCl.Core/Base/Salsa20Base.cs
> +        readonly ISalsa20Core _salsa20Core;
Could you make this access modifier implicit?

2022-11-08 01:33 UTC, daviddesmet commented on src/NaCl.Core/Base/Salsa20Base.cs
> +        internal protected abstract void SetInitialState(Span<uint> state, ReadOnlySpan<byte> nonce, int counter);
Something minor... the access modifier should be `protected internal`, just need to fix the ordering.

2022-11-08 01:33 UTC, daviddesmet commented on src/NaCl.Core/Base/Salsa20Base.cs
> +#if INTRINSICS
I wonder if we do need the preprocessor directive since we are checking if the hardware supports it

2022-11-08 01:33 UTC, daviddesmet commented on src/NaCl.Core/Base/Salsa20Base.cs
> +        internal protected static void ShuffleState(Span<uint> state)
Something minor... the access modifier should be `protected internal`, just need to fix the ordering.

2022-11-08 01:33 UTC, daviddesmet commented on src/NaCl.Core/Base/Salsa20BaseIntrinsics.cs
> +﻿#if INTRINSICS
I wonder if we do need the preprocessor directive since we are checking if the hardware supports it

2022-11-08 01:33 UTC, daviddesmet commented on src/NaCl.Core/Base/SalsaCore/Salsa20CoreIntrinsics.cs
> +﻿#if INTRINSICS
I wonder if we do need the preprocessor directive since we are checking if the hardware supports it

2022-11-08 01:33 UTC, daviddesmet commented on src/NaCl.Core/Base/SalsaCore/Salsa20CoreIntrinsics.cs
> +    const int BLOCK_SIZE_IN_INTS = Snuffle.BLOCK_SIZE_IN_INTS;
Could you make this access modifier implicit?

2022-11-08 01:33 UTC, daviddesmet commented on src/NaCl.Core/Base/SalsaIntrinsics/Salsa256.cs
> +﻿#if INTRINSICS
I wonder if we do need the preprocessor directive since we are checking if the hardware supports it

2022-11-08 01:33 UTC, daviddesmet commented on src/NaCl.Core/Base/SalsaIntrinsics/Salsa512.cs
> +﻿#if INTRINSICS
I wonder if we do need the preprocessor directive since we are checking if the hardware supports it

2022-11-08 01:33 UTC, daviddesmet commented on src/NaCl.Core/Base/SalsaIntrinsics/Salsa64.cs
> +﻿#if INTRINSICS
I wonder if we do need the preprocessor directive since we are checking if the hardware supports it

2022-11-08 01:33 UTC, daviddesmet commented on src/NaCl.Core/Base/Snuffle.cs
> +        internal protected readonly int InitialCounter;
Something minor... the access modifier should be `protected internal`, just need to fix the ordering.

2022-11-08 01:33 UTC, daviddesmet commented on src/NaCl.Core/NaCl.Core.csproj
> -    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
Would be nice to leave this on.

2022-11-08 01:33 UTC, daviddesmet commented on src/NaCl.Core/Salsa20.cs
> +        internal protected override void SetInitialState(Span<uint> state, ReadOnlySpan<byte> nonce, int counter)
Something minor... the access modifier should be `protected internal`, just need to fix the ordering.

2022-11-08 01:33 UTC, daviddesmet commented on src/NaCl.Core/XSalsa20.cs
> +        internal protected override void SetInitialState(Span<uint> state, ReadOnlySpan<byte> nonce, int counter)
Something minor... the access modifier should be `protected internal`, just need to fix the ordering.

2022-11-08 01:33 UTC, daviddesmet commented on test/NaCl.Core.Benchmarks/ChaCha20Benchmark.cs
> +﻿namespace NaCl.Core.Benchmarks
We could switch to scoped namespace declaration here since we already using it on the other files =)

2022-11-08 01:33 UTC, daviddesmet commented on test/NaCl.Core.Benchmarks/Program.cs
> +            c.Encrypt();
Do we need to call the benchmark like this? Maybe it was some test code that somehow got into here?

2022-11-08 01:33 UTC, daviddesmet commented on test/NaCl.Core.Benchmarks/Program.cs
> +            c.Encrypt();
Do we need to call the benchmark like this? Maybe it was some test code that somehow got into here?

2022-11-08 01:33 UTC, daviddesmet commented on test/NaCl.Core.Benchmarks/Salsa20Benchmark.cs
> +﻿namespace NaCl.Core.Benchmarks
We could switch to scoped namespace declaration here since we already using it on the other files =)

2022-11-08 01:33 UTC, daviddesmet commented on test/NaCl.Core.Benchmarks/XSalsa20Benchmark .cs
> +﻿namespace NaCl.Core.Benchmarks
We could switch to scoped namespace declaration here since we already using it on the other files =)

2022-11-08 01:33 UTC, daviddesmet commented on test/NaCl.Core.SimdTests/ChaCha20IntrinsicsTests .cs
> +﻿namespace NaCl.Core.SimdTests
We could switch to scoped namespace declaration here since we already using it on the other files =)

2022-11-08 01:33 UTC, daviddesmet commented on test/NaCl.Core.SimdTests/ChaCha20IntrinsicsTests .cs
> +    using NaCl.Core.SimdTests.Vectors;
I don't think this using is needed

2022-11-08 01:33 UTC, daviddesmet commented on test/NaCl.Core.SimdTests/ChaCha20ScalarTests.cs
> +    using NaCl.Core.SimdTests.Vectors;
I don't think this using is needed since above it you are already specifying `using Vectors;`

2022-11-08 01:33 UTC, daviddesmet commented on test/NaCl.Core.SimdTests/Salsa20IntrinsicsTests.cs
> +    using NaCl.Core.SimdTests.Vectors;
I don't think this `using` is needed since above it you are already specifying `using Vectors;`

2022-11-08 01:33 UTC, daviddesmet commented on test/NaCl.Core.SimdTests/Salsa20ScalarTests.cs
> +    using NaCl.Core.SimdTests.Vectors;
I don't think this `using` is needed since above it you are already specifying `using Vectors;`

2022-11-08 01:44 UTC, daviddesmet commented
@TimothyMakkison my apologies for the late follow-up, it has been hectic over here.

Thanks a ton for pulling this big task off, I added a few comments to the PR; most of them are minor stuff.

I also noticed a PowerShell script but I didn't see it being called from DevOps, is it something you intended to do? The build defined in this project uses Cake, we could set the environment variable in there afaik; I will need to investigate further into that. Perhaps we can use that and just define tests that should be running with specific environment variables without the need to update the GitHub actions.

Last but not least, I wonder if you could work on the coverage a little bit more since we dropped quite a lot with this PR, you can check codecov from above.

2022-11-08 01:49 UTC, daviddesmet requested changes

2022-11-08 01:49 UTC, daviddesmet commented on src/NaCl.Core/Base/ChaCha20BaseIntrinsics.cs
> +            throw new Exception("Error this vectorisation is not supported on this CPU");
We should avoid using the base `Exception` and instead use `NotSupportedException`, I would also suggest using a more specific error message like `The SSE3 vectorisation is not supported on the current CPU`.

2022-11-08 01:49 UTC, daviddesmet commented on src/NaCl.Core/Base/ChaCha20BaseIntrinsics.cs
> +            throw new Exception("Error this vectorisation is not supported on this CPU");
We should avoid using the base `Exception` and instead use `NotSupportedException`, I would also suggest using a more specific error message like `The SSE3 vectorisation is not supported on the current CPU`.

2022-11-08 01:49 UTC, daviddesmet commented on src/NaCl.Core/Base/ChaCha20BaseIntrinsics.cs
> +            throw new Exception("Error this vectorisation is not supported on this CPU");
We should avoid using the base `Exception` and instead use `NotSupportedException`, I would also suggest using a more specific error message like `The SSE3 vectorisation is not supported on the current CPU`.

2022-11-08 01:49 UTC, daviddesmet commented on src/NaCl.Core/Base/Salsa20BaseIntrinsics.cs
> +            throw new Exception("Error this vectorisation is not supported on this CPU");
We should avoid using the base `Exception` and instead use `NotSupportedException`, I would also suggest using a more specific error message like `The SSE3 vectorisation is not supported on the current CPU`.

2022-11-08 01:49 UTC, daviddesmet commented on src/NaCl.Core/Base/Salsa20BaseIntrinsics.cs
> +            throw new Exception("Error this vectorisation is not supported on this CPU");
We should avoid using the base `Exception` and instead use `NotSupportedException`, I would also suggest using a more specific error message like `The SSE3 vectorisation is not supported on the current CPU`.

2022-11-08 01:49 UTC, daviddesmet commented on src/NaCl.Core/Base/Salsa20BaseIntrinsics.cs
> +            throw new Exception("Error this vectorisation is not supported on this CPU");
We should avoid using the base `Exception` and instead use `NotSupportedException`, I would also suggest using a more specific error message like `The SSE3 vectorisation is not supported on the current CPU`.

2022-11-08 18:00 UTC, TimothyMakkison commented
Thanks for the review. I got sidetracked and forgot about this PR so it's unfinished. 

> I wonder if we do need the preprocessor directive since we are checking if the hardware supports it

`System.Runtime.Intrinsics.X86` is only [supported for .NET 3.0+](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.intrinsics.x86.sse3?view=net-7.0#applies-to). Intrinsics code won't compile for libraries that multi target versions unless we use a preprocessor.


> Could you make this access modifier implicit?

Not sure what you mean by implicit, do you mean `private`?


> We could switch to scoped namespace declaration here since we already using it on the other files =)

Should I convert all the files in the solution to scoped namespaces?


> I also noticed a PowerShell script but I didn't see it being called from DevOps, is it something you intended to do? The build defined in this project uses Cake, we could set the environment variable in there afaik; 

Sorry I was using the benchmark code and powershell script for testing and forgot to remove them. I'll modify the cake file.


Do you have an opinion on the refactor? 

The logic up to 202ff15 was [fairly simple](https://github.com/daviddesmet/NaCl.Core/blob/202ff15f1fc0fa74e842cbe384581e490f1f42c1/src/NaCl.Core/Base/ChaCha20Base.cs); the intrinsics code was added with pre processing and an IsSupported check. This has the advantage of not touching the api, keeping the code/code flow the same and adding minimal additional code and files.

Commit 4d68791 separates the intrinsic and non intrinsic code from SalsaBase/ChaChaBase creating individual files for them, SalsaBase/ChaChaBase act as a facade [calling the internal IChaChaCore interface](https://github.com/daviddesmet/NaCl.Core/blob/4d68791ea70192c160e6afa640271530db5c7ccb/src/NaCl.Core/Base/ChaCha20Base.cs) for all methods. This has the disadvantage of adding a lot of code, altering a lot of code to keep the api the same, duplicating code and arguably being overly complex.

I'll probably undo the refactor unless you prefer it, I thinks it's too complicated, harder to maintain, and isn't needed if the CI will test SIMD and non SIMD versions. Should also improve the code coverage and reduce duplication.

2022-11-08 18:12 UTC, TimothyMakkison commented
Thanks for the review. I got sidetracked and forgot about this PR so it's unfinished. 

> I wonder if we do need the preprocessor directive since we are checking if the hardware supports it

`System.Runtime.Intrinsics.X86` is only [supported for .NET 3.0+](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.intrinsics.x86.sse3?view=net-7.0#applies-to). Intrinsics code won't compile for libraries that multi target versions unless we use a preprocessor.


> Could you make this access modifier implicit?

Not sure what you mean by implicit, do you mean `private`?


> We could switch to scoped namespace declaration here since we already using it on the other files =)

Should I convert all the files in the solution to scoped namespaces?


> I also noticed a PowerShell script but I didn't see it being called from DevOps, is it something you intended to do? The build defined in this project uses Cake, we could set the environment variable in there afaik; 

Sorry I was using the benchmark code and powershell script for testing and forgot to remove them. I'll modify the cake file.


Do you have an opinion on the refactor? 

The logic up to 202ff15 was [fairly simple](https://github.com/daviddesmet/NaCl.Core/blob/202ff15f1fc0fa74e842cbe384581e490f1f42c1/src/NaCl.Core/Base/ChaCha20Base.cs); the intrinsics code was added with pre processing and an IsSupported check. This has the advantage of not touching the api, keeping the code/code flow the same and adding minimal additional code and files.

Commit 4d68791 separates the intrinsic and non intrinsic code from SalsaBase/ChaChaBase creating individual files for them, SalsaBase/ChaChaBase act as a facade [calling the internal IChaChaCore interface](https://github.com/daviddesmet/NaCl.Core/blob/4d68791ea70192c160e6afa640271530db5c7ccb/src/NaCl.Core/Base/ChaCha20Base.cs) for all methods. This has the disadvantage of adding a lot of code, altering a lot of code to keep the api the same, duplicating code and arguably being overly complex.

I'll probably undo the refactor unless you prefer it, I thinks it's too complicated, harder to maintain, and isn't needed if the CI will test SIMD and non SIMD versions. Should also improve the code coverage and reduce duplication.

2022-11-09 15:08 UTC, TimothyMakkison commented
> Yeah, I agree with that. It added a lot of maintainability complexity, if we limit the scope of the supported .NET versions we can stick with the first logic you proposed.
> I think we can drop .NET 3 and just stick with the supported versions going forward. Supporting obsolete versions of .NET just adds a lot of maintainability headaches.

The "refactor" was added to make the code testable, with the CI and cake file this thankfully isn't needed. This pr is compatible with all the different versoins of .NET it just requires a couple of pre processor checks.

- Updated the cake file, NET 7 RC 2 has broken my sdk so I can't install the cake tool and test it. Hopefully it works 🤞 
- Reverted the changes to `Salsa20Base` and `ChaCha20Base`.
- Deleted intrinsic/scalar tests.
- Optimized the shuffle function for `Salsa64`, this used a different instruction set so I updated the guard checks.
- To reduce the scope of this pr I haven't updated all the namespaces. I'm tempted to create a code cleanup pr changing the namespaces, exception parameters, empty arrays and unused fields etc.

2022-11-17 00:43 UTC, daviddesmet commented
> * To reduce the scope of this PR I haven't updated all the namespaces. I'm tempted to create a code cleanup pr changing the namespaces, exception parameters, empty arrays and unused fields etc.

Yeah, sounds great!

> Do you think it would be worth getting someone who knows intrinsics to double check this? This was my first time using intrinisics/unsafe code in this way.

That would be nice but I really don't know anyone from my side. :/

2022-11-17 00:59 UTC, TimothyMakkison commented
I had the cunning idea of submitting a pr to the bouncycastle project. Give them a performance bump for large cipherstreams and have another set of eyes look at the implementations. Once I get a grasp of `IDigest` I'll make a pr

2026-07-03 18:56 UTC, daviddesmet commented
Intrinsics added, closing...

2026-07-03 18:56 UTC, closed without merging